package org.fuse.usecase.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11.fuse-710022-redhat-00001
 * 2019-04-24T10:06:35.369+08:00
 * Generated source version: 3.1.11.fuse-710022-redhat-00001
 * 
 */
@WebServiceClient(name = "CustomerWSService", 
                  wsdlLocation = "file:/Users/adityanugraha/workspace/jboss/workspace-fuse20190422/ai_advanced_labs/agile_integration_advanced_labs/code/fuse/05_migrate_fuse6/legacy-soap-rest-wrapper/customerService.wsdl",
                  targetNamespace = "http://service.usecase.fuse.org/") 
public class CustomerWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.usecase.fuse.org/", "CustomerWSService");
    public final static QName CustomerWSPort = new QName("http://service.usecase.fuse.org/", "CustomerWSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/adityanugraha/workspace/jboss/workspace-fuse20190422/ai_advanced_labs/agile_integration_advanced_labs/code/fuse/05_migrate_fuse6/legacy-soap-rest-wrapper/customerService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/adityanugraha/workspace/jboss/workspace-fuse20190422/ai_advanced_labs/agile_integration_advanced_labs/code/fuse/05_migrate_fuse6/legacy-soap-rest-wrapper/customerService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CustomerWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CustomerWS
     */
    @WebEndpoint(name = "CustomerWSPort")
    public CustomerWS getCustomerWSPort() {
        return super.getPort(CustomerWSPort, CustomerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerWS
     */
    @WebEndpoint(name = "CustomerWSPort")
    public CustomerWS getCustomerWSPort(WebServiceFeature... features) {
        return super.getPort(CustomerWSPort, CustomerWS.class, features);
    }

}
